spring.application.name=shinpo

spring.datasource.url=jdbc:postgresql://localhost:5432/shinpo
spring.datasource.username=shinpo
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
